### ISSUE TITLE
Can't find 'LLM Vision' in HACS or normal Integrations page search.

### ISSUE THREAD

**Issue by Billium28** [valentinfrlch/ha-llmvision#102]
I'm trying to install this tool so I can implement it with my HA and Unifi Camera. I cannot find LLM Vision when using the HACs search nor using the normal HA integrations page. Is there a different way to find that particular install?

**Comment by valentinfrlch** [comment]
Hi! Right now you need to add the repository to HACS first (still waiting to get approved to the default HACS list). You can find a button in the readme. HACS will then prompt you to restart your home assistant after which you can add LLM Vision on the integration page.

**Comment by Billium28** [comment]
Ok, I see it. Thanks!!
