### ISSUE TITLE
Blueprint Error - Error rendering variables: UndefinedError: 'dict object' has no attribute 'payload_json'

### ISSUE THREAD

**Issue by erwinvol** [valentinfrlch/ha-llmvision#106]
### Bug Description
I'm receiving the following error in my HA log about every 2 minutes:
Error rendering variables: UndefinedError: 'dict object' has no attribute 'payload_json'

When I look at the trace log of the notification, it seems to run every 2 minutes, I dont know why its triggering, there is nothing happening at the camera. Tracelog is below

AI Event Summary (LLM Vision v1.3.1)

### Service Call
- id: '1732673727019'
  alias: Notification - Activity at the front door
  description: ''
  use_blueprint:
    path: valentinfrlch/event_summary.yaml
    input:
      mode: Frigate
      notify_device:
      - 24bf1f32ccf3de6784227347ec4bb815
      camera_entities:
      - camera.frontyard
      motion_sensors:
      - binary_sensor.front_yard_doorbell_person_occupancy
      tap_navigate: /lovelace/3
      provider: Google Gemini
      model: gemini-1.5-flash

### Logs
Trace log:
{
  "trace": {
    "last_step": null,
    "run_id": "9b0e0469f28301d65952bf5cd5797690",
    "state": "stopped",
    "script_execution": null,
    "timestamp": {
      "start": "2024-11-27T02:33:41.046689+00:00",
      "finish": "2024-11-27T02:33:41.047416+00:00"
    },
    "domain": "automation",
    "item_id": "1732673727019",
    "error": "UndefinedError: 'dict object' has no attribute 'payload_json'",
    "trigger": null,
    "trace": {},
    "config": {
      "variables": {
        "important": false,
        "cooldown": 10,
        "mode": "Frigate",
        "preview_mode": "Live Preview",
        "notify_devices": [
          "24bf1f32ccf3de6784227347ec4bb815",
          "0f92e8d7bac91833c4d2aca04d6cba8a"
        ],
        "device_name_map": "{% set ns = namespace(device_names=[]) %} {% for device_id in notify_devices %}\n  {% set device_name = device_attr(device_id, \"name\") %}\n  {% set sanitized_name = \"mobile_app_\" + device_name | lower | regex_replace(\"[^a-z0-9_\\- ]\", \"\") | replace(\" \", \"_\") | replace(\"-\", \"_\") %}\n  {% set ns.device_names = ns.device_names + [sanitized_name] %}\n{% endfor %} {{ ns.device_names }}\n",
        "camera_entities_list": [
          "camera.volbell"
        ],
        "motion_sensors_list": [],
        "camera_entity": "{% if mode == 'Camera' %}\n  {% if motion_sensors_list and not \"camera\" in trigger.entity_id %}\n    {% set index = motion_sensors_list.index(trigger.entity_id) %}\n    {{ camera_entities_list[index] }}\n  {% else %}\n    {{ trigger.entity_id }}\n  {% endif %}\n{% else %}\n  {{ trigger.payload_json['after']['camera'] }}\n{% endif %}\n",
        "tag": "{% if mode == 'Frigate' %}\n  {{ trigger.payload_json['after']['camera'] + int(as_timestamp(now()))|string }}\n{% else %}\n  {{ camera_entity + int(as_timestamp(now()))|string }}\n{% endif %}\n",
        "group": "{% if mode == 'Frigate' %}\n  {{ trigger.payload_json['after']['camera'] }}\n{% else %}\n  {{ camera_entity }}\n{% endif %}\n",
        "label": "{% if mode == 'Frigate' %}\n  {{ trigger.payload_json['after']['label']|capitalize }} seen\n{% else %}\n  Motion detected\n{% endif %}\n",
        "camera": "{% if mode == 'Frigate' %}\n  {{ trigger.payload_json['after']['camera'].replace('_', ' ')|capitalize }}\n{% else %}\n  {{ camera_entity.replace(\"camera.\", \"\").replace(\"_\", \" \")|capitalize }}\n{% endif %}\n",
        "video": "{% if mode == 'Frigate' %}\n  /api/frigate/notifications/{{ trigger.payload_json['after']['id'] }}/clip.mp4\n{% else %} {% endif %}\n",
        "image": "{% if mode == 'Frigate' %}\n  ''\n{% else %}\n  {% if preview_mode == 'Live Preview' %}\n    {{ '/api/camera_proxy/' + camera_entity }}\n  {% else %}\n    /local/llmvision/{{camera_entity.replace(\"camera.\", \"\")}}_0.jpg\n  {% endif %}\n{% endif %}\n",
        "importance_prompt": "Your job is to classify security events based on cctv footage. Your options: \"passive\" if an event seems unimportant, \"time-sensitive\" if important and \"critical\" for suspicious events. Use \"critical\" only for possible burglaries and similar events. \"time-sensitive\" could be a courier at the front door or an event of similar importance. Reply with these replies exactly.\n"
      },
      "triggers": [
        {
          "platform": "mqtt",
          "topic": "frigate/events",
          "id": "frigate_trigger"
        },
        {
          "platform": "state",
          "entity_id": [
            "camera.volbell"
          ],
          "to": "recording",
          "id": "camera_trigger"
        },
        {
          "platform": "state",
          "entity_id": [],
          "to": "on",
          "id": "motion_sensor_trigger"
        }
      ],
      "conditions": [
        {
          "condition": "template",
          "value_template": "{% if mode == 'Frigate' %}\n  {{ trigger.payload_json[\"type\"] == \"end\" and (state_attr(this.entity_id, 'last_triggered') is none or (now() - state_attr(this.entity_id, 'last_triggered')).total_seconds() / 60 > cooldown) and ('camera.' + trigger.payload_json['after']['camera']|lower) in camera_entities_list }}\n{% else %}\n  {{ state_attr(this.entity_id, 'last_triggered') is none or (now() - state_attr(this.entity_id, 'last_triggered')).total_seconds() / 60 > cooldown }}\n{% endif %}\n"
        }
      ],
      "actions": [
        {
          "choose": [
            {
              "conditions": [
                {
                  "condition": "template",
                  "value_template": "{{ important }}"
                }
              ],
              "sequence": [
                {
                  "alias": "Decide Important",
                  "choose": [
                    {
                      "conditions": [
                        {
                          "condition": "template",
                          "value_template": "{{ mode == 'Frigate'}}"
                        }
                      ],
                      "sequence": [
                        {
                          "action": "llmvision.image_analyzer",
                          "data": {
                            "image_entity": "{{ ['camera.' + trigger.payload_json['after']['camera']|lower] }}",
                            "provider": "01JDHQRET9KAYA4S3B26S7B5WD",
                            "model": "gemini-1.5-flash",
                            "message": "{{importance_prompt}}",
                            "include_filename": true,
                            "target_width": 1280,
                            "detail": "low",
                            "max_tokens": 3,
                            "temperature": 0.1
                          },
                          "response_variable": "importance"
                        }
                      ]
                    },
                    {
                      "conditions": [
                        {
                          "condition": "template",
                          "value_template": "{{ mode == 'Camera' }}"
                        }
                      ],
                      "sequence": [
                        {
                          "action": "llmvision.image_analyzer",
                          "data": {
                            "image_entity": "{{[camera_entity]}}",
                            "provider": "01JDHQRET9KAYA4S3B26S7B5WD",
                            "model": "gemini-1.5-flash",
                            "message": "{{importance_prompt}}",
                            "include_filename": true,
                            "target_width": 1280,
                            "detail": "low",
                            "max_tokens": 3,
                            "temperature": 0.1
                          },
                          "response_variable": "importance"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "choose": [
            {
              "conditions": [
                {
                  "condition": "template",
                  "value_template": "{{ importance is defined and importance.response_text|lower == 'passive' }}"
                }
              ],
              "sequence": [
                {
                  "stop": "Event is not important"
                }
              ]
            }
          ]
        },
        {
          "choose": [
            {
              "conditions": [
                {
                  "condition": "template",
                  "value_template": "{{ image != '' or video != '' }}"
                }
              ],
              "sequence": [
                {
                  "alias": "Send instant notification to notify devices",
                  "repeat": {
                    "for_each": "{{device_name_map}}",
                    "sequence": [
                      {
                        "action": "notify.{{ repeat.item }}",
                        "data": {
                          "title": "{{ label }}",
                          "message": "{{camera}}",
                          "data": {
                            "video": "{{video if video != '' else None}}",
                            "image": "{{image if image != '' else None}}",
                            "entity_id": "{{camera_entity if mode=='Camera' and preview_mode=='Live Preview'}}",
                            "url": "/lovelace/3",
                            "clickAction": "/lovelace/3",
                            "tag": "{{tag}}",
                            "group": "{{group}}",
                            "interruption-level": "{{importance.response_text|lower if importance is defined else 'active'}}"
                          }
                        }
                      }
                    ]
                  }
                }
              ]
            }
          ]
        },
        {
          "alias": "Analyze event",
          "choose": [
            {
              "conditions": [
                {
                  "condition": "template",
                  "value_template": "{{ mode == 'Frigate' }}"
                }
              ],
              "sequence": [
                {
                  "action": "llmvision.video_analyzer",
                  "data": {
                    "event_id": "{{ trigger.payload_json['after']['id'] }}",
                    "provider": "01JDHQRET9KAYA4S3B26S7B5WD",
                    "model": "gemini-1.5-flash",
                    "message": "Summarize what's happening in the camera feed (one sentence max). Don't describe the scene! If there is a person, describe what they're doing and what they look like. If they look like a courier mention that! If nothing is happening, say so.",
                    "remember": false,
                    "include_filename": true,
                    "max_frames": 3,
                    "target_width": 1280,
                    "detail": "low",
                    "max_tokens": 20,
                    "temperature": 0.1
                  },
                  "response_variable": "response"
                }
              ]
            },
            {
              "conditions": [
                {
                  "condition": "template",
                  "value_template": "{{ mode == 'Camera' }}"
                }
              ],
              "sequence": [
                {
                  "action": "llmvision.stream_analyzer",
                  "data": {
                    "image_entity": "{{[camera_entity]}}",
                    "duration": 5,
                    "provider": "01JDHQRET9KAYA4S3B26S7B5WD",
                    "model": "gemini-1.5-flash",
                    "message": "Summarize what's happening in the camera feed (one sentence max). Don't describe the scene! If there is a person, describe what they're doing and what they look like. If they look like a courier mention that! If nothing is happening, say so.",
                    "remember": false,
                    "include_filename": true,
                    "max_frames": 3,
                    "target_width": 1280,
                    "detail": "low",
                    "max_tokens": 20,
                    "temperature": 0.1,
                    "expose_images": "{{true if preview_mode == 'Snapshot'}}"
                  },
                  "response_variable": "response"
                }
              ]
            }
          ]
        },
        {
          "choose": [
            {
              "conditions": [
                {
                  "condition": "template",
                  "value_template": "{{ image != '' or video != '' }}"
                }
              ],
              "sequence": [
                {
                  "alias": "Send instant notification to notify devices",
                  "repeat": {
                    "for_each": "{{device_name_map}}",
                    "sequence": [
                      {
                        "action": "notify.{{ repeat.item }}",
                        "data": {
                          "title": "{{ label }}",
                          "message": "{{response.response_text}}",
                          "data": {
                            "video": "{{video if video != '' else None}}",
                            "image": "{{image if image != '' else None}}",
                            "entity_id": "{{camera_entity if mode=='Camera' and preview_mode=='Live Preview'}}",
                            "url": "/lovelace/3",
                            "clickAction": "/lovelace/3",
                            "tag": "{{tag}}",
                            "group": "{{group}}",
                            "interruption-level": "passive"
                          }
                        }
                      }
                    ]
                  }
                }
              ]
            }
          ]
        }
      ],
      "id": "1732673727019",
      "alias": "Notification - Activity at the front door",
      "description": ""
    },
    "blueprint_inputs": {
      "id": "1732673727019",
      "alias": "Notification - Activity at the front door",
      "description": "",
      "use_blueprint": {
        "path": "valentinfrlch/event_summary.yaml",
        "input": {
          "mode": "Frigate",
          "notify_device": [
            "24bf1f32ccf3de6784227347ec4bb815",
            "0f92e8d7bac91833c4d2aca04d6cba8a"
          ],
          "camera_entities": [
            "camera.volbell"
          ],
          "motion_sensors": [],
          "tap_navigate": "/lovelace/3",
          "provider": "01JDHQRET9KAYA4S3B26S7B5WD",
          "model": "gemini-1.5-flash"
        }
      }
    },
    "context": {
      "id": "01JDNQF6XP64DM001XEVRP66ZF",
      "parent_id": "01JDNQF6XAADS7TD8K1GG9PK3X",
      "user_id": null
    }
  },
  "logbookEntries": []
}

### Additional context
Logger: homeassistant.components.automation.notification_activity_at_the_front_door
Source: components/automation/__init__.py:688
integration: Automation (documentation, issues)
First occurred: 9:15:54 PM (3 occurrences)
Last logged: 9:19:05 PM

Error rendering variables: UndefinedError: 'dict object' has no attribute 'payload_json'

**Comment by valentinfrlch** [comment]
It seems frigate sends new events in frigate/events. In Home Assistant under the MQTT integration, you can record events. Could help to understand why the events are fired.
![image](https://github.com/user-attachments/assets/2e1bbed8-3290-4882-bec8-da26329272f7)

**Comment by valentinfrlch** [comment]
Closing this as inactive. Feel free to reopen this issue if you need help!
