### ISSUE TITLE
Unable to Install ?  404 - https://hacs.xyz/docs/setup/download/

### ISSUE THREAD

**Issue by FPA-ChrisLaird** [valentinfrlch/ha-llmvision#109]
### Bug Description
Following installation instructions here: https://llm-vision.gitbook.io/getting-started says recommended installation method is to follow instructions provided by this link,  https://hacs.xyz/docs/setup/download/.   This link results in a 404.

Edit: I worked it out, but the instructions may be confusing for some.

**Comment by valentinfrlch** [comment]
Thanks, the HACS url has apparently changed. Docs have been updated with the new link.
