### ISSUE TITLE
Persistent Notification Option w/ video/snapshot

### ISSUE THREAD

**Issue by ViceBooster** [valentinfrlch/ha-llmvision#116]
**Is your feature request related to a problem? Please describe.**
I am using the camera option, and would like a persistent notification with video/image of the frames caught by the AI. Similarly to how the mobile app notification is sent.

**Describe the solution you'd like**
A toggle to turn on/off persistent notifications. 

**Describe alternatives you've considered**
Creating the feature myself by adding to the blueprint has the images never being over written, so with something like this (see below) in the blueprint we just get new notifications with the same image over and over.

`  - choose:
      - conditions:
          - condition: template
            value_template: "{{ image != '' or video != '' }}"
        sequence:
          - alias: "Send instant notification to notify devices"
            repeat:
              for_each: "{{device_name_map}}"
              sequence:
                - action: "notify.{{ repeat.item }}"
                  data:
                    title: "{{ label }}"
                    message: "{{response.response_text}}"
                    data:
                      video: "{{video if video != '' else None}}"
                      image: "{{image if image != '' else None}}"
                      entity_id: "{{camera_entity if mode=='Camera' and preview_mode=='Live Preview'}}"
                      url: !input tap_navigate #iOS
                      clickAction: !input tap_navigate #Android
                      tag: "{{tag}}"
                      group: "{{group}}"
                      interruption-level: passive
          - service: persistent_notification.create
            data_template:
              title: "{{ label }}"
              message: "{{ response.response_text }}{% if image %}\n![Camera Image]({{image}}){% endif %}{% if video %}\nVideo: {{ video }}{% endif %}"
              notification_id: "{{tag}}"
             `

**Comment by valentinfrlch** [comment]
The reason it will always show the same picture is because images aren't cached and will be loaded every time. Currently only the latest image is stored to save space. I'll see if there's a good workaround because I don't want to change the way images are stored at the moment.
For now, in your automation you can store the snapshot in a custom folder and use a timestamp as its name. This should enable different images for different persistent notifications.
The blueprint also has a lot of issues that need to be addressed first, but if you have a working automation, feel free to share it!

**Comment by ViceBooster** [comment]
Hey just for clarification sake, you said I could use a custom folder and a timestamp. However the path seems to be baked into the integrations media_handler.py as seen here.

`    
async def _save_clip(self, clip_data=None, clip_path=None, image_data=None, image_path=None):

# Ensure dir exists

await self.hass.loop.run_in_executor(None, partial(os.makedirs, "/config/www/llmvision", exist_ok=True))
` 

and here,

` 
if expose_images:
await self._save_clip(image_data=resized_image, image_path=f"/config/www/llmvision/{image_entity.replace('camera.', '')}.jpg")
`

Are you suggesting I change this, and the blueprint?

**Comment by valentinfrlch** [comment]
Sorry for the confusion. You'd need to create your own automation and capture a snapshot, store it in a folder and then feed that to the action directly.

**Comment by valentinfrlch** [comment]
Feel free to reopen this at any time if you have any questions! Closing this as unplanned for now, as there are some bugs that need to be fixed first. Once the blueprint actually works well we can still implement persistent notifications.
