### ISSUE TITLE
Stream Analyzer not fetching realtime stream

### ISSUE THREAD

**Issue by ghostracer34** [valentinfrlch/ha-llmvision#117]
when using the stream analyzer with generic cameras using  a rtsp feed the captured frames are all the same and usually from 30 minutes before the request is made.

Version: 1.3.1

action: llmvision.stream_analyzer
metadata: {}
data:
  remember: false
  duration: 2
  max_frames: 8
  include_filename: true
  target_width: 1280
  max_tokens: 100
  temperature: 0.4
  expose_images: true
  provider: ""
  message: >-
    ""
  image_entity:
    - camera.down_drive
    - camera.up_drive
response_variable: response

I've had a little success with a workaround of recording a small clip in the automation before starting the analyzer but kinda ruins the timings on certain cameras.

**Comment by valentinfrlch** [comment]
In Developer Tools > States can you confirm that the attribute `entity_picture` is present for your cameras? When you append the value of `entity_picture` to your home assistant url, you should see the _current_ frame.

**Comment by ghostracer34** [comment]
When I do that I get a frame from what's seems like the camera last activity in HA so hours ago in this case when I refresh the current frame then appears I tried on another generic camera and same thing happened but needed 2 refreshes to get current frame

**Comment by valentinfrlch** [comment]
What camera are you using? Is the generic camera generated from an rtsp stream?

**Comment by ghostracer34** [comment]
They are swann cctv camaras using the rtsp streams from the nvr to create the generic camera in HA

**Comment by valentinfrlch** [comment]
Could be the NVR not serving a realtime stream. There is not much that can be done on the integration side as the issue for this seems to be upstream. Feel free to reopen this if you have any questions!
