### ISSUE TITLE
Add option to send evenly spaced video frames to LLM

### ISSUE THREAD

**Issue by rsteckler** [valentinfrlch/ha-llmvision#119]
**Is your feature request related to a problem? Please describe.**
The 'highest' motion frames often don't tell the story of what happened in the video and result in descriptions that 'miss the point'

**Describe the solution you'd like**
I'd like an option to tell LLMVision to generate x number of frames, evenly spaced, including the first and last frames from the video.  For example, if the video is 5 FPS and 15 seconds long, it would have 75 frames total.  An option like 
```
- frames_to_generate: 10
```
would send frames 1 and 75, then send the evenly distributed frames in-between:
1, 8, 17, 25, 33, 42, 51, 58, 66, 75

**Describe alternatives you've considered**

**Additional context**

**Comment by valentinfrlch** [comment]
This is actually what was in place previously. You are right, the frames with the most movement might not tell the whole story. But neither will evenly spaced frames, as they could miss the most important part of the event. I have tested both systems thoroughly and I believe that the current implementation is better.

There is currently a potential bug (#85) that mixes up the order of frames. Is that your experience as well?

**Comment by rsteckler** [comment]
> This is actually what was in place previously. You are right, the frames with the most movement might not tell the whole story. But neither will evenly spaced frames, as they could miss the most important part of the event. I have tested both systems thoroughly and I believe that the current implementation is better.
> 
> There is currently a potential bug (#85) that mixes up the order of frames. Is that your experience as well?

Would still love the option, but totally get if you want to close this as not planned.

I'll comment in the other thread on my own images to keep your issues list consistent.

**Comment by valentinfrlch** [comment]
Thanks for your understanding!
