### ISSUE TITLE
Ollama only working with single image not stream and video analyzing?

### ISSUE THREAD

**Issue by torsteinelv** [valentinfrlch/ha-llmvision#128]
Been trying for a long time to get ollama working and it does only support image analyz? Not the other functions?

**Comment by valentinfrlch** [comment]
Can you share your action call and the error that you get? Ollama does support multiple images per call.

**Comment by torsteinelv** [comment]
`action: llmvision.stream_analyzer
data:
  remember: false
  duration: 1
  max_frames: 1
  include_filename: false
  target_width: 1280
  detail: low
  max_tokens: 100
  temperature: 0.2
  expose_images: false
  provider: 01JEKNBFS3MWB1W5Z5DF3V55VH
  model: llava
  message: test
  image_entity:
    - camera.garasje2
    - `
Example. I never see any request been made to the ollama server. Only when using image

**Comment by torsteinelv** [comment]
when I go with stream i can see in frigate log that the snapshots a are collected but i can see in the log for homeassistant:
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:2032
First occurred: 20:06:23 (1 occurrences)
Last logged: 20:06:23

websocket_api script: Error executing script. Error for call_service at pos 1: Request failed: [Errno 104] Connection reset by peer

--
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:820
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 20:06:23 (1 occurrences)
Last logged: 20:06:23

[140709403477040] Request failed: [Errno 104] Connection reset by peer

--
Log details (ERROR)
This error originated from a custom integration.
Logger: custom_components.frigate
Source: helpers/update_coordinator.py:411
integration: Frigate ([documentation](https://github.com/blakeblackshear/frigate), [issues](https://github.com/blakeblackshear/frigate-hass-integration/issues))
First occurred: 20:03:33 (6 occurrences)
Last logged: 20:07:48

Error fetching frigate data:


dont know if this is relevant or what log files I need to look at?

This only happens with stream and video analyzer.

**Comment by torsteinelv** [comment]
traffic was blocked async
