### ISSUE TITLE
Audio support?

### ISSUE THREAD

**Issue by torsteinelv** [valentinfrlch/ha-llmvision#129]
Google api support entire videos with audio support : https://cloud.google.com/vertex-ai/generative-ai/docs/samples/generativeaionvertexai-gemini-video-with-audio

Would be cool to use with combination of frigate.

**Comment by valentinfrlch** [comment]
As far as I know only Google supports this right now. Also, LLM Vision does not send the entire video (again, not all providers support video). Could be interesting in the future but this is not planned for the near future.
