### ISSUE TITLE
Is there a Discord/place for discussion for ha-llmvision?

### ISSUE THREAD

**Issue by jonlove234** [valentinfrlch/ha-llmvision#130]
Can't find anyone in the Home Assistant Discord talking about it, and the HA forums are always a bit tricky for "live" discussions.

Thanks!

**Comment by valentinfrlch** [comment]
At the moment there is only the HA forum (and well github). I don't know how many people would be on discord, so not sure if live discussions would be much easier with a small discord community.

**Comment by jonlove234** [comment]
That's fair re: unclear how useful discord would be.

If it's helpful, in the process to get mine working - which it now seems to be - I discovered the following things. I'm not sure if you want to add a FAQ to the gitbook documentation?

Notifications with 404 errors and notifications with a black video (that had controls/etc, but was totally black): I was getting these both regularly, and at first I thought it was a network issue. It turns out that they were different issues. On the 404 errors, I had certain alerts being generated by Frigate where Frigate alerted but was not setup to record any clip. When I managed those off in Frigate, those seem to have gone away. I used some Object zones to block object alerts I didn't want.

On the black video, I think my camera's resolution was too high - and maybe resulted in too large a video for iOS. I lowered my POE camera from 4512x2512 (I forgot what frame rate) to 2560x1440 at 10FPS, and in both cases kept the max bitrate to be 8192, and this "black video" problem seems to have gone away. I'd be curious if anyone else has experienced it and/or discovered what the highest video size that iOS notifications will support is. Or if the issue is not size and something else.

@valentinfrlch I was also looking at the automation, and maybe I missed it, but I don't see the `Remember` option being used. Is it, and I'm missing it?

Anyway, thanks - it's been great, especially as I work through the things I need to fix on my end to get it working well.

I guess this message was partly why I was curious about a chat in case I could have bounced these issues around with other users. 😁

**Comment by jonlove234** [comment]
Also, one thing I might suggest in the blueprint is adding:

```
trace:
  stored_traces: 25

```

Maybe it can be added separately, but given that Frigate MQTT can be noisy, the default limit of 5 stored_traces made it really tough for me.

Thanks!
