### ISSUE TITLE
Failed to fetch frigate clip

### ISSUE THREAD

**Issue by blueharford** [valentinfrlch/ha-llmvision#131]
### Bug Description
i cannot get the integration to work, i keep getting "Failed to fetch frigate clip 1734115929.356327-qh1m17"

but when i put the clip URL in and prepend the home assistant baseurl it shows the clip

**Version**:  v1.3.1

### Service Call

```yaml
using AI Event Summary (LLM Vision v1.3.1) blueprint
```

### Logs

```
Failed to fetch frigate clip 1734118475.54774-8xayu0

```

**Comment by valentinfrlch** [comment]
What are your network settings for Home Assistant (Settings>System>Network)? Make sure you have a valid url there:
![image](https://github.com/user-attachments/assets/dcfcd516-5ac8-4190-953b-3cdc20708f28)

**Comment by mrsofa** [comment]
I am stealing this thread as the OP is not active.
I have the same error and I want to let you know that my network settings are valid. The local and public networks are configured correctly.


Also I'm adding the screenshot of the full issue.

I want to add I'm running frigate in a separate lxc that is not accessible outside of my home network. I only do snapshots and no recordings. Also the weird thing is that running the LLM vision in developer tools>actions and linking the same camera entity works, so im guessing it has to do something with the template that I took from your site.

![Screenshot_20241219_162813_Home Assistant](https://github.com/user-attachments/assets/588e37be-f331-4fee-890c-5693cffe1c39)

**Comment by blueharford** [comment]
Updating the network fixed it for me, but the delay was massive. 

I think this could be faster if we used the snapshot instead of waiting for and uploading the clip. Would love to see this updated

**Comment by valentinfrlch** [comment]
Thanks for the suggestion! This is a good idea!

**Comment by srvoets** [comment]
I am getting this issue, and network is valid, what is the fix?
