### ISSUE TITLE
while parsing a block mapping in "<unicode string>", line 1, column 1: blueprint: ^ expected <block end>, but found '-' in "<unicode string>", line 432, column 1: - delay: 00:{{cooldown|int}}:00 ^

### ISSUE THREAD

**Issue by danistst** [valentinfrlch/ha-llmvision#139]
### Bug Description
I get an error when trying to import the blueprint. 

while parsing a block mapping in "<unicode string>", line 1, column 1: blueprint: ^ expected <block end>, but found '-' in "<unicode string>", line 432, column 1: - delay: 00:{{cooldown|int}}:00 ^

**Version**: 30 LLM Vision v1.3.1 

Blueprint with latest commit on Dec 22

**Comment by valentinfrlch** [comment]
#137 The issue is mentioned here as well. Thanks for raising this!

**Comment by SleepyMoz** [comment]
@valentinfrlch  I have created a pull request with a fix. Do you mind reviewing it.

**Comment by valentinfrlch** [comment]
Thanks @SleepyMoz! The blueprint imports correctly now.

**Comment by rappazzo** [comment]
Sorry, that's my bad.
