### ISSUE TITLE
Camera mode does not work - blueprint

### ISSUE THREAD

**Issue by LarsLautrup** [valentinfrlch/ha-llmvision#141]
I just created an automation using the newly fixed blueprint - and configured it for camera mode.
Added an motion trigger and the automation is triggered as expected.
But - the automation ends every time after checking if Frigate-mode is used - see the picture.

![image](https://github.com/user-attachments/assets/8ad57758-99a2-4738-9665-630788efce52)

I'm not an expert in this, so hopefully someone is able to tell me, what I have done wrong. I've checked the settings multiple times and everything looks ok...

/Lars.

**Comment by LarsLautrup** [comment]
![image](https://github.com/user-attachments/assets/ea73c7ea-681d-47f6-a86d-63b17eb30573)

**Comment by valentinfrlch** [comment]
Thanks for reporting! The issue should now be fixed. Please reimport the blueprint and try again. If the issue persists feel free to reopen this issue!
