### ISSUE TITLE
Option to create MP4 from captured frames

### ISSUE THREAD

**Issue by slflowfoon** [valentinfrlch/ha-llmvision#147]
**Is your feature request related to a problem? Please describe.**

The primary motivation for this feature is to address the issue of incompatibility with GIF notifications on Android devices.

**Describe the solution you'd like**

Whilst GIF notifications are not supported, MP4 notifications are. By having the option to generate MP4 videos from the captured frames prior to SSIM scoring, we can support animated notifications just like iOS.

**Describe alternatives you've considered**

https://github.com/slflowfoon/ha-llmvision/blob/main/custom_components/llmvision/media_handlers.py

I have implemented this to my integration as a test and currently appears to be working. Proposed changes:

**MP4 Video Output:**
- Modify the `add_streams` function to generate MP4 video files. This will involve using `ffmpeg` to combine the captured frames into an MP4 video.

- The MP4 video will be saved to `/config/www/llmvision/` with a filename based on the camera entity name.

**Configurable Video Parameters:**
- Introduce the ability to configure the target FPS (`video_target_fps`) and target width (`video_target_width`) of the generated MP4 video. Default values for target FPS and width will be set to 2 and 512, respectively.

**Timestamped Temporary Directories:**

- Modify the temporary directory creation for frames to include a timestamp in the folder name. This will ensure that each recording session has a unique temporary directory, preventing potential conflicts and making it easier to manage temporary files.

----

- The `ffmpeg` command will be used to convert the captured frames into an MP4 video.
- The `video_target_fps` and `video_target_width` methods will allow users to set the desired FPS and width for the generated video.
- The temporary directory names will include a timestamp to ensure uniqueness.

**Additional context**

**Comment by valentinfrlch** [comment]
I assume this is related to the blueprint notifications. LLM Vision doesn't create a GIF for the notifications. There are different modes (Live Preview and Snapshot). In both cases Home Assistant handles notifications and is responsible for streaming e.g. live previews to your phone. If Android doesn't support live previews that would be something that would have to be changed in the notification implementation of Home Assistant.

Feel free to reopen this if I misunderstood!
