### ISSUE TITLE
response is undefined

### ISSUE THREAD

**Issue by mpez22** [valentinfrlch/ha-llmvision#148]
Hi all, and thanks Valentin not only for an amazing integration, but also for being one of the most dedicated and friendly contributors in the HA community. 🤝

I've been searching far and wide to fix an issue with a script of mine, but I haven't been able to find a solution so here I am. Any hint is much appreciated.

My use case: I've built a script that helps me find my dog when he's in the garden, by passing screenshots of my cameras to AI and have it reply with a specific string if it sees a dog in one of the pictures. The script is called via an Alexa routine. Alexa then is supposed to reply with the area/camera in which the dog has been recognized by AI, or with a fallback message in case he can't be seen in any of the screenshots (he's very good at hiding...).

Unfortunately, I keep getting an error saying the response variable is undefined, as per the message below:

`Template variable error: 'camera1_response' is undefined when rendering '{{ camera1_response.response_text == "CANE PRESENTE" }}'`

"camera1_response" should be the variable returned when processing a screenshot of the "camera1" camera (I have 5 cameras in total, so 5 variables should be returned). "CANE PRESENTE" is the string the AI should return if it sees a dog in the picture.

Here's the complete yaml code for the script. Note: I'm using Gemini 2.0 Flash Experimental as the API calls are currently free (feels like cheating haha). I've tested it via Google AI studio and it works like a charm. The prompt says "If you see a Boston terrier in the picture return "DOG PRESENT" otherwise return "NO DOG". I've set the temperature very low so it returns exactly that string.

`alias: Dov'è il cane
description: >-
  Scatta snapshot con tutte le telecamere, cerca il cane e restituisce la
  posizione.
sequence:
  - action: alexa_media.update_last_called
    metadata: {}
    data: {}
  - parallel:
      - action: camera.snapshot
        target:
          entity_id: camera.camera1_main
        data:
          filename: /config/www/snapshots/camera1.jpg
      - action: camera.snapshot
        target:
          entity_id: camera.camera2_main
        data:
          filename: /config/www/snapshots/camera2.jpg
      - action: camera.snapshot
        target:
          entity_id: camera.camera3_main
        data:
          filename: /config/www/snapshots/camera3.jpg
      - action: camera.snapshot
        target:
          entity_id: camera.camera4
        data:
          filename: /config/www/snapshots/camera4.jpg
      - action: camera.snapshot
        target:
          entity_id: camera.camera5
        data:
          filename: /config/www/snapshots/camera5.jpg
  - parallel:
      - action: llmvision.image_analyzer
        metadata: {}
        data:
          include_filename: false
          target_width: 1280
          max_tokens: 50
          temperature: 0.1
          provider: 01JFR6DA2EMK2C8MF69R186A37
          model: gemini-2.0-flash-exp
          message: >-
            Se vedi un Boston Terrier nella foto, rispondi "CANE PRESENTE".
            Altrimenti, rispondi "NESSUN CANE".
          image_file: /config/www/snapshots/camera1.jpg
        response_variable: camera1_response
      - action: llmvision.image_analyzer
        metadata: {}
        data:
          include_filename: false
          target_width: 1280
          max_tokens: 50
          temperature: 0.1
          provider: 01JFR6DA2EMK2C8MF69R186A37
          model: gemini-2.0-flash-exp
          message: >-
            Se vedi un Boston Terrier nella foto, rispondi "CANE PRESENTE".
            Altrimenti, rispondi "NESSUN CANE".
          image_file: /config/www/snapshots/camera2.jpg
        response_variable: camera2_response
      - action: llmvision.image_analyzer
        metadata: {}
        data:
          include_filename: false
          target_width: 1280
          max_tokens: 50
          temperature: 0.1
          provider: 01JFR6DA2EMK2C8MF69R186A37
          model: gemini-2.0-flash-exp
          message: >-
            Se vedi un Boston Terrier nella foto, rispondi "CANE PRESENTE".
            Altrimenti, rispondi "NESSUN CANE".
          image_file: /config/www/snapshots/camera3.jpg
        response_variable: camera3_response
      - action: llmvision.image_analyzer
        metadata: {}
        data:
          include_filename: false
          target_width: 1280
          max_tokens: 50
          temperature: 0.1
          provider: 01JFR6DA2EMK2C8MF69R186A37
          model: gemini-2.0-flash-exp
          message: >-
            Se vedi un Boston Terrier nella foto, rispondi "CANE PRESENTE".
            Altrimenti, rispondi "NESSUN CANE".
          image_file: /config/www/snapshots/camera4.jpg
        response_variable: camera4_response
      - action: llmvision.image_analyzer
        metadata: {}
        data:
          include_filename: false
          target_width: 1280
          max_tokens: 50
          temperature: 0.1
          provider: 01JFR6DA2EMK2C8MF69R186A37
          model: gemini-2.0-flash-exp
          message: >-
            Se vedi un Boston Terrier nella foto, rispondi "CANE PRESENTE".
            Altrimenti, rispondi "NESSUN CANE".
          image_file: /config/www/snapshots/camera5.jpg
        response_variable: camera5_response
  - choose:
      - conditions:
          - condition: template
            value_template: |
              {{ camera1_response.response_text == "CANE PRESENTE" }}
        sequence:
          - action: notify.alexa_media_last_called
            data:
              message: Il cane è nell'area 1.
              data:
                type: tts
        alias: Trovato in area 1
      - conditions:
          - condition: template
            value_template: |
              {{ camera2_response.response_text == "CANE PRESENTE" }}
        sequence:
          - action: notify.alexa_media_last_called
            data:
              message: Il cane è nell'area 2.
              data:
                type: tts
        alias: Trovato in area 2
      - conditions:
          - condition: template
            value_template: |
              {{ camera3_response.response_text == "CANE PRESENTE" }}
        sequence:
          - action: notify.alexa_media_last_called
            data:
              message: Il cane è nell'area camera3.
              data:
                type: tts
        alias: Trovato in area 3
      - conditions:
          - condition: template
            value_template: |
              {{ camera4_response.response_text == "CANE PRESENTE" }}
        sequence:
          - action: notify.alexa_media_last_called
            data:
              message: Antenore è nell'area 4.
              data:
                type: tts
        alias: Trovato in area 4
      - conditions:
          - condition: template
            value_template: |
              {{ camera5_response.response_text == "CANE PRESENTE" }}
        sequence:
          - action: notify.alexa_media_last_called
            data:
              message: Antenore è nell'area 5.
              data:
                type: tts
        alias: Trovato in area 5
  - action: notify.alexa_media_last_called
    data:
      message: Oh no, non sono riuscita a trovare il cane in nessuna delle aree.
      data:
        type: tts
    enabled: true
mode: single
icon: mdi:dog
`

Any idea on what I'm missing? 

Thanks in advance, cheers from Italy!

**Comment by valentinfrlch** [comment]
Thanks for the kind words, glad you like the integration!

I think it could be because of the `parallel` block you have. I am unfamiliar with it, but in the `choose` block later on the variables are checked. I think that part fails because `camera1_response` could be undefined. 

If I understand correctly you want to check all cameras to see if a dog is present and in which camera. Since `image_analyzer` can take multiple camera entities as input you could just do:
```yaml
action: llmvision.image_analyzer
data:
  target_width: 1280
  max_tokens: 100
  temperature: 0.1
  provider: <your provider ID>
  model: gemini-2.0-flash-exp
  message: <your prompt>
  image_entity:
    - camera.front_door
    - camera.garden
    - <etc...>
  response_variable: camera_response
```

Then continue to check if camera_response contains DOG PRESENT with a template condition
```yaml
"{{"DOG PRESENT" in camera_response}}"
```

Let me know if that helped!

**Comment by slflowfoon** [comment]
This definitely seems to be a Home Assistant issue that I've encountered as well. It looks like [Reddit](https://www.reddit.com/r/homeassistant/comments/1hh3xd3/parallel_action_with_response_variable/) isn't aware of a workaround for this yet either.

The best workaround I've found is to update the response to an input text helper and then create a condition based on the value of the helper. Here's an example:

```yaml
  - metadata: {}
    data:
      value: "{{ camera_response.response_text }}"
    target:
      entity_id: input_text.camera_response
    action: input_text.set_value
```

**Comment by mpez22** [comment]
Thank you so much guys, I just found out that there are no global variables in HA 😭😭😭

That's why the response variable coming from LLM Vision, being inside of a `parallel` block, was undefined outside of that block and couldn't be used.

I ended up doing as @slflowfoon suggested and used an input text helper. Seems like it's the only solution for now.

Here's a link for reference: [https://www.home-assistant.io/docs/scripts/#scope-of-variables](https://www.home-assistant.io/docs/scripts/#scope-of-variables)

Thank you again and happy new year!

**Comment by kisjeth** [comment]
> Thank you so much guys, I just found out that there are no global variables in HA 😭😭😭
> 
> That's why the response variable coming from LLM Vision, being inside of a `parallel` block, was undefined outside of that block and couldn't be used.
> 
> I ended up doing as [@slflowfoon](https://github.com/slflowfoon) suggested and used an input text helper. Seems like it's the only solution for now.
> 
> Here's a link for reference: https://www.home-assistant.io/docs/scripts/#scope-of-variables
> 
> Thank you again and happy new year!

Posso chiederti come hai configurato l'input text? Non capisco come trasportare il responso dentro l'helper

**Comment by mpez22** [comment]
> Posso chiederti come hai configurato l'input text? Non capisco come trasportare il responso dentro l'helper

Hey, in my use case I simply check if the response equals a certain value:

```
condition: template
value_template: "{{ response.response_text == \"YOUR EXPECTED RESPONSE\" }}"
```

and if yes I update the value of the helper with a "set value" action, like this:

```
action: input_text.set_value
metadata: {}
data:
  value: This is the new value of the helper.
target:
  entity_id: input_text.your_helper
```

Then I use the value of the helper in the final notification the script returns, and after that I set again the helper to the default value.

Hope this helps! Ciao :)
