### ISSUE TITLE
Assuming I installed correctly, where does this input a notification?

### ISSUE THREAD

**Issue by Billium28** [valentinfrlch/ha-llmvision#150]
I think I installed this correctly, it's been a couple weeks since I've had time to work on anything related. Where would this LLMVision notification be occurring? Do I make an automation to send to my phone? Is there a UI?

**Comment by valentinfrlch** [comment]
LLM Vision is an integration. You can build an automation to send the analysis to your phone or use the blueprint (although there have been some issues with that lately). If you want to test LLM Vision, you can do so in developer tools. Please see the examples and documentation (link in readme).
