### ISSUE TITLE
Fetch Failed: Cannot Connect to Host

### ISSUE THREAD

**Issue by ZWood15** [valentinfrlch/ha-llmvision#45]
### Bug Description
Getting an error when attempting to call an action using LLM Vision

HA 2024.8.0
LLM Vision 1.0.1

### Service Call

action: llmvision.image_analyzer
data:
  provider: Google
  include_filename: false
  target_width: 1280
  detail: high
  max_tokens: 100
  temperature: 0.5
  message: Describe what you see in the image, be detailed in your description.
  image_entity:
    - camera.frontyard

### Logs

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:797
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:46:59 PM (6 occurrences)
Last logged: 11:00:54 PM

[140601808554448] Fetch failed: Cannot connect to host 10.0.1.117:8123 ssl:default [[SSL] record layer failure (_ssl.c:1000)]
[140601808554448] No image input provided
[140601285001024] Fetch failed: Cannot connect to host 10.0.1.117:8123 ssl:default [[SSL] record layer failure (_ssl.c:1000)]

### Additional context
Recieving the error when connecting directly via IP address or when accessing via a custom domain served over https

**Comment by valentinfrlch** [comment]
Can you check _Settings > System > Network > Home Assistant URL_?
To fetch images the url set there is used:
<img width="625" alt="image" src="https://github.com/user-attachments/assets/9d09b391-c468-4c46-b1e1-cb6b80c4774b">

**Comment by ZWood15** [comment]
That worked! The URL setting was what was causing issue, sorry for the trouble and thanks so much. Excited to use this integration!!

**Comment by valentinfrlch** [comment]
No worries, glad to hear it works!
