### ISSUE TITLE
Support base url for openai

### ISSUE THREAD

**Issue by lurebat** [valentinfrlch/ha-llmvision#46]
**Is your feature request related to a problem? Please describe.**
There are plenty of openai-compatible llms that could be used interchangeably with this, as well as people who use openai behind a proxy.

Currently, the only parameter you can provide to the openai integration is the api key.

**Describe the solution you'd like**

Add an optional base url parameter for the openai integration.  
The openai sdk already accepts it as a parameter, and it would allow using the repo with openai-compatible llms or behind a proxy.

**Comment by valentinfrlch** [comment]
That sounds like a great idea. I'll add a "Custom (OpenAI compatible)" provider soon.

**Comment by Dominoxan** [comment]
Hi, 
Sorry for sticking to someone's else thread.

Would it be possible also to somehow add LMStudio method?

[https://lmstudio.ai/docs/local-server](url)

It's local LLM server, very user friendly with great GUI. tried "Local AI" but it does use different API call via POST
![lmstudio_example](https://github.com/user-attachments/assets/0e02c300-af98-4b5a-9d9d-652d271ecddf)
 method:

GET /v1/models
POST /v1/chat/completions
POST /v1/embeddings            
POST /v1/completions

**Comment by valentinfrlch** [comment]
I'll look into it

**Comment by valentinfrlch** [comment]
I can't find any mention of sending images or supporting multimodal models. It seems to only support text.

**Comment by Dominoxan** [comment]
Well, it does support vision models but not via GUI, let me dig thru support files. Anyway, thanks for checking and sorry for bothering.

**Comment by valentinfrlch** [comment]
@Dominoxan If you find something please open a new feature request. Always happy to support new providers (especially self-hosted)
