### ISSUE TITLE
how create a automation with the data?

### ISSUE THREAD

**Issue by Coketrd** [valentinfrlch/ha-llmvision#66]
very nice, thankyou. BUT ohne question. how you save the answer and send it to a media player or a notificationservice? i cant find a example you to use it after create the image discription.

can you make a example how i can do this after run the service?

**Comment by valentinfrlch** [comment]
Of course! 
See the wiki for examples: https://llm-vision.gitbook.io/examples/examples/scripts#capture-an-image-from-a-camera-entity-and-ask-about-it

This example sends the output to a tts service.

**Comment by Coketrd** [comment]
thankyou its working great :)
