### ISSUE TITLE
Feature Request: Support for Notify Groups in Home Assistant Blueprint to Enhance Efficiency and Reduce Costs

### ISSUE THREAD

**Issue by zeppelinlg** [valentinfrlch/ha-llmvision#81]
**Is your feature request related to a problem? Please describe.**
The current blueprint in the repository supports sending notifications to individual devices, but it lacks functionality for notifying a group of devices. This limitation is particularly problematic as each automation trigger requires a separate API call, potentially increasing costs when using paid notification services. It is frustrating for users who need to notify multiple devices about the same event efficiently and cost-effectively.

**Describe the solution you'd like**
I propose enhancing the blueprint to include the ability to send notifications to notify groups as documented in Home Assistant's official documentation on group notifications (https://www.home-assistant.io/integrations/group/#notify-groups). Users should be able to specify a group of devices as the notification target in the blueprint configuration, instead of only specifying individual device_ids. This option would allow notifications to be sent to multiple devices within a single API call, potentially reducing costs and simplifying configuration.

**Describe alternatives you've considered**
An alternative solution could be to modify the current blueprint to allow specifying a list of individual device_ids directly. Users could input multiple device IDs separated by commas or in a list format, which would still send notifications to all specified devices in one go. Although this provides a direct solution to notify multiple devices, it can still be cumbersome to manage and might not address issues related to API cost-efficiency as effectively as notify groups would.

**Additional context**
The ability to send notifications to a group rather than individual devices is particularly crucial for environments where cost-efficiency and simplicity are paramount. This is especially true in scenarios such as shared households, community spaces, or small businesses where multiple devices need to receive the same alerts simultaneously. By integrating group notifications, we can leverage bulk messaging capabilities, thereby reducing the number of API calls necessary and consequently keeping operational costs lower.

**Comment by valentinfrlch** [comment]
I am working on this and it will be in the next update. 
You are right, running multiple instances of this blueprint in parallel could lead to increased cost. There may be some other problems as the LLM Vision will write files to disk. When running in parallel, there may be some bad interleavings. Use with caution! 

Thanks for the suggestion though!

**Comment by TScalzott** [comment]
Modifying the blueprint to support saving the analysis response to a named Helper might also help with this as a workaround, while expanding the possibilities. 

With such, an additional automation could notify more than one device. It would also enable the trivial integration into cards on a dashboard.

**Comment by valentinfrlch** [comment]
Multi-device notifications have been implemented in v1.3.1 of the blueprint.

**Comment by lguillemenot-placeloop** [comment]
Thanks for adding the notify group feature to the blueprint!
I'll test it out as soon as possible.

**Comment by valentinfrlch** [comment]
You're welcome! Just a heads up: There is a bug that prevents the blueprint from working correctly if a phone's name has special characters in it. I am working on a fix.

**Comment by hankfic** [comment]
Notify groups still aren't showing up in the Blueprint device list. Is there a way to specify in YAML then?  Any updates on phone names with symbols?
