### ISSUE TITLE
Customize notification title and icon

### ISSUE THREAD

**Issue by johnuopini** [valentinfrlch/ha-llmvision#96]
I think blueprint should be updated to also include an option to change notification title and icon just like SgtBatten blueprint OR even better it would be nice to be able to use the description in SgtBatten blueprint.

**Comment by valentinfrlch** [comment]
Idea is good but there are a few bugs in the blueprint that need to be addressed first.
You can always "take control" of SgtBatten's blueprint and add a call to llm vision (use [the llm vision blueprint](https://github.com/valentinfrlch/ha-llmvision/blob/main/blueprints/event_summary.yaml) as inspiration). If you put something together feel free to send a PR!
