### ISSUE TITLE
Unable to get OpenAI Extended Conversations to prompt the calendar for past events

### ISSUE THREAD

**Issue by PsychOsmosis** [valentinfrlch/ha-llmvision#97]
After configuring OpenAI Extended Conversations to query past events, every time I try to use the assistant to do so, I get the following response :

"The calendar entity "LLM_Vision_Events" is currently in an "off" state, so it's not providing any information about recent or past events"

It has been driving me mad, as I can't find any info about this issue online...
The Event Calendar is configured in the LLM Vision integration (with 0 days to remember all).
The Event Calendar correctly shows past notifications.

What's the cause of this ?

**Comment by PsychOsmosis** [comment]
I also added the spec as per the guide underneath the default spec in the OpenAI Extended Conversations configuration.

**Comment by PsychOsmosis** [comment]
![image](https://github.com/user-attachments/assets/f2f6be30-fb8f-4052-a903-a28c83f357dc)

**Comment by valentinfrlch** [comment]
Calendar entities in Home Assistant are always in an `off` state when there is no active event. To get OpenAI Extended Conversation to actually search past events, youneed to add the 'spec' from the docs:
https://llm-vision.gitbook.io/getting-started/asking-about-events#asking-about-events

**Comment by PsychOsmosis** [comment]
I already added the spec though.
I pasted it underneath the default one.
Isn't that what I'm supposed to do?

**Comment by valentinfrlch** [comment]
That should be correct. Maybe you need to specifically prompt the LLM to use that script when you ask about events.

**Comment by PsychOsmosis** [comment]
I tried adding the specification, and this is what I get afterwards.

"Unfortunately, there are no events recorded in the calendar "LLM Vision Events" that I can retrieve using the get_events function."

That's weird. The events are clearly there...

**Comment by valentinfrlch** [comment]
Could be context threshold as well, so increasing that might help. I have set it to 10000.

**Comment by PsychOsmosis** [comment]
I'm running my own model llama3.2-vision:11b and I think it's just dumb as a sack of bricks...

What's the name of the field where the event description gets output in the calendar entries?
I will try telling it to specifically look at this field.

**Comment by valentinfrlch** [comment]
Do you use the blueprint? What action do you use?

**Comment by PsychOsmosis** [comment]
Yes I use the blueprint.

I forked it in order to edit the trigger conditions ("entered_zones" value and time conditions), but the rest of the blueprint is unedited.

**Comment by valentinfrlch** [comment]
The generated response is in the `response_text` field. If your response variable is `response` then you can access it with `{{response.response_text}}`. This is true for all actions except `data_analyzer` (which doesn't return anything).

**Comment by PsychOsmosis** [comment]
I just tried it with ChatGPT, and it works flawlessly.

So yeah, it's just that my model is as dumb as a sack of bricks.
Or maybe a vision model is unsuited for parsing text?

So I'll just use ChatGPT for the Assistant feature and I'll keep using my model to process the camera feed.

Thank you very much for your help !

**Comment by valentinfrlch** [comment]
The 90b model is probably better (don't know by how much though). It also requires significantly more VRAM so that is likely not a good alternative. 
Unfortunately, the open source models I've tried that can be self hosted, have all been very disappointing. 

Btw, here's a chart comparing the available models:
![image](https://github.com/user-attachments/assets/2c6549b7-84a2-4f99-ae1f-d1fc862edc56)
(Gemini has a free tier in some regions)
