### ISSUE TITLE
Sensor Update in Video Analyzer

### ISSUE THREAD

**Issue by Paul-Vdp** [valentinfrlch/ha-llmvision#99]
It would be super useful to have Video Analyzer update a sensor, based on the message prompt - of course besides its current operation of describing the video scene.
Use case : because Frigate keeps generating far too many false positives I feed my Frigate Alerts into Video Analyzer to verify if they really contain images of a person. It would be very useful if then Video Analyzer updates some sensor based upon this verification, besides describing the scene.
This sensor can then be used to steer the further downstream process ...

**Comment by valentinfrlch** [comment]
I think it would make sense to enable video input for the existing `data_analyzer`. There is a bug in `data_analyzer` at the moment that needs to be fixed first, but I'll try to include this in the next update.
(Might be a while since I don't have a lot of time right now)

**Comment by Paul-Vdp** [comment]
I guess you are the best judge of that. I only hope it is clear that I am looking for a solution to get both things done with just ONE call to llmvision, i.e. setting a sensor AND getting the scene description ...

**Comment by TiddlyWiddly** [comment]
I agree this would be super useful. Sometimes the notifications are too long to display on iOS and I get sad when I can't read the end. Would also be useful to keep track of the last video or images in camera mode so you can validate that the prompt actually describes what's happening.

**Comment by TiddlyWiddly** [comment]
I did find a hacky workaround by "taking control" of the blueprint and using an input_text helper to capture the LLM response at the end of the automation, but it's not ideal as you need to create 1 for every camera manually and then go diving into yaml to set it at notification time. Also truncates at 100 characters for some reason even though I've set all my input_texts to max of 255. 

In snapshot mode you can grab the image file from local/llmvision/camera_0.jpg and use as a picture card, but Lovelace wants to cache it in the browser (works okay on iOS mobile though) so it doesn't refresh.

**Comment by valentinfrlch** [comment]
For now, use two calls: One to get the description of the video and a second one to update the sensor. Data analyzer should be fixed in v1.3.5.
